# Generated by Django 4.1 on 2022-08-09 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_clientAccountCreator", models.BooleanField(default=False)),
                ("is_controlleur", models.BooleanField(default=False)),
                ("is_client", models.BooleanField(default=False)),
            ],
            options={"db_table": "login",},
        ),
        migrations.CreateModel(
            name="ComptesEspece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IdDepositaire", models.IntegerField(null=True)),
                ("DateCreation", models.DateField(default=datetime.datetime.now)),
                ("Web", models.CharField(max_length=100, null=True)),
                ("Etat", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("IdClasse", models.IntegerField(null=True)),
                ("IdNatureIdt", models.IntegerField(null=True)),
                ("IdPays", models.IntegerField(null=True)),
                ("NatureClient", models.CharField(max_length=100, null=True)),
                ("Etat", models.CharField(max_length=100, null=True)),
                ("IdCategorieAvoir", models.IntegerField(null=True)),
                ("RaisonSociale", models.CharField(max_length=100, null=True)),
                ("Matricule", models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImputationsEspeces",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sens", models.IntegerField(null=True)),
                ("Montant", models.IntegerField(null=True)),
                ("DateImputation", models.DateField(max_length=30, null=True)),
                ("IdSDBCompte", models.IntegerField(null=True)),
                ("NatureClient", models.CharField(max_length=100, null=True)),
                ("DateValeur", models.DateField(max_length=30, null=True)),
                ("Etat", models.CharField(max_length=100, null=True)),
                ("IdDateValeur", models.IntegerField(null=True)),
                ("Nature", models.CharField(max_length=100, null=True)),
                ("DateEtat", models.DateField(max_length=30, null=True)),
                ("libelle", models.CharField(max_length=100, null=True)),
                (
                    "IdCompteEspece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.comptesespece",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comptesespece",
            name="IdClient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.client"
            ),
        ),
    ]
